"""
Generate the standalone sample-output document.

The brief asks (optionally) for "predictions or a ranked list for one or two
example chat contexts". This produces both, in one self-contained readable file:

  1. Raw pCTR predictions on real held-out impressions, next to what actually
     happened, so the numbers can be sanity-checked rather than taken on trust.
  2. Full ranked slates for two contrasting chat contexts, with every scoring
     term broken out and a plain-English reason per ad.

Writes reports/sample_output.md
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from simula.config import ARTIFACTS, RANDOM_SEED, REPORTS  # noqa: E402
from simula.data import add_time_columns, join_characters, load_characters, load_impressions  # noqa: E402
from simula.ranker import (  # noqa: E402
    BudgetPacer,
    Candidate,
    CandidateRanker,
    Context,
    FatigueTracker,
)
from simula.serving import ModelScorer  # noqa: E402

OUT: list[str] = []


def say(s: str = "") -> None:
    OUT.append(s)


# Named candidates so the output is readable. Attributes are real (C-feature)
# tuples sampled from the log; the labels are illustrative.
CANDIDATES = [
    #  id               advertiser    pos   C14   C15  C16   C17  C18 C19    C20  C21   bid  max_tier
    ("AD_MOBILE_GAME",  "ADV_GAMES",    1, 15708, 300, 250, 1722, 2,  35, 100083,  79, 3.20, "mature"),
    ("AD_DATING_APP",   "ADV_DATE",     1, 20362, 320,  50, 2333, 0,  39,     -1, 157, 4.50, "mature"),
    ("AD_ENERGY_DRINK", "ADV_BEVERAGE", 0, 17753, 320,  50, 1993, 0,  35,     -1,  23, 1.80, "sfw"),
    ("AD_BANK_CARD",    "ADV_FINANCE",  0,  4687, 320,  50,  423, 3,  39,     -1,  32, 5.00, "sfw"),
    ("AD_NEW_RPG",      "ADV_GAMES",    1, 21611, 320,  50, 2480, 2,  35, 100084,  33, 2.40, "mature"),
    ("AD_STREAMING",    "ADV_MEDIA",    0, 18993, 320,  50, 2161, 0, 167,     -1,  71, 1.20, "suggestive"),
]

AD_IMPRESSIONS = {
    "AD_MOBILE_GAME": 45_000, "AD_DATING_APP": 30_000, "AD_ENERGY_DRINK": 12_000,
    "AD_BANK_CARD": 22_000, "AD_NEW_RPG": 40, "AD_STREAMING": 15,
}


def build_candidates() -> list[Candidate]:
    return [
        Candidate(ad_id=a, advertiser_id=adv, banner_pos=pos, C14=c14, C15=c15,
                  C16=c16, C17=c17, C18=c18, C19=c19, C20=c20, C21=c21,
                  bid_cpc=bid, max_safety_tier=cap)
        for (a, adv, pos, c14, c15, c16, c17, c18, c19, c20, c21, bid, cap) in CANDIDATES
    ]


def ctx_from_row(r) -> Context:
    return Context(
        character_id=str(r.character_id), conversation_turn=int(r.conversation_turn),
        session_msg_count=int(r.session_msg_count), hour=int(r.hour),
        site_id=str(r.site_id), site_domain=str(r.site_domain),
        site_category=str(r.site_category), app_id=str(r.app_id),
        app_domain=str(r.app_domain), app_category=str(r.app_category),
        device_id=str(r.device_id), device_ip=str(r.device_ip),
        device_model=str(r.device_model), device_type=int(r.device_type),
        device_conn_type=int(r.device_conn_type), C1=int(r.C1),
        safety_tier=str(r.safety_tier), creator_type=str(r.creator_type),
        num_interactions=int(r.num_interactions),
        created_at=str(pd.Timestamp(r.created_at).date()),
    )


def main() -> None:
    if not (ARTIFACTS / "model.txt").exists():
        print("No trained model. Run scripts/03_train.py first.")
        sys.exit(1)

    df = join_characters(add_time_columns(load_impressions()), load_characters())
    test = df[df["day"].isin([141029, 141030])].reset_index(drop=True)
    preds = np.load(ARTIFACTS / "test_preds.npy")
    assert len(test) == len(preds)
    test["p_ctr"] = preds

    chars = load_characters().set_index("character_id")
    scorer = ModelScorer()

    say("# Sample output")
    say()
    say("Two things the brief asked for as optional: raw CTR predictions, and a "
        "ranked candidate list for example chat contexts. Both are below, "
        "generated by `scripts/08_sample_output.py`.")

    # ==================================================================
    say()
    say("## 1. CTR predictions on held-out impressions")
    say()
    say("Real rows from the held-out window (days 141029-30), never seen during "
        "training. `p_ctr` is the model's prediction; `clicked` is what actually "
        "happened.")
    say()
    say("Sampled across the probability range rather than at random, and showing "
        "one clicked and one non-clicked example at each level. A purely random "
        "sample of 18 rows at a 17% base rate would usually contain almost no "
        "clicks, which would be representative but useless for eyeballing.")
    say()

    # Stratified across the probability range, and balanced on outcome within
    # each stratum, so the table shows what both outcomes look like at a given
    # predicted probability. The decile table below carries the real evidence.
    test["_bucket"] = pd.qcut(test["p_ctr"], 6, labels=False, duplicates="drop")
    parts = []
    for _, d in test.groupby("_bucket"):
        for lab in (1, 0):
            sub = d[d["click"] == lab]
            if len(sub):
                parts.append(sub.sample(min(2, len(sub)), random_state=RANDOM_SEED))
    sample = pd.concat(parts).sort_values("p_ctr", ascending=False)
    show = pd.DataFrame({
        "p_ctr": sample["p_ctr"].round(4),
        "clicked": sample["click"].astype(int).values,
        "character": [
            chars.loc[c, "character_name"] if c in chars.index else "?"
            for c in sample["character_id"].astype(str)
        ],
        "tier": sample["safety_tier"].astype(str).values,
        "turn": sample["conversation_turn"].values,
        "site_id": sample["site_id"].astype(str).values,
        "banner_pos": sample["banner_pos"].values,
    })
    say("```")
    say(show.to_string(index=False))
    say("```")

    say()
    say("Aggregate check over the whole held-out window "
        f"({len(test):,} impressions):")
    say()
    say(f"- mean predicted CTR: **{test['p_ctr'].mean():.4f}**")
    say(f"- actual CTR:         **{test['click'].mean():.4f}**")
    say(f"- ratio:              **{test['p_ctr'].mean()/test['click'].mean():.4f}** "
        "(1.000 would be perfectly calibrated in aggregate)")
    say()
    say("Grouped into deciles of predicted probability, to show the model "
        "separates rather than just hitting the average:")
    say()
    dec = test.groupby(pd.qcut(test["p_ctr"], 10, labels=False, duplicates="drop")).agg(
        n=("click", "size"), predicted=("p_ctr", "mean"), actual=("click", "mean")
    ).round(4)
    dec.index.name = "decile"
    say("```")
    say(dec.to_string())
    say("```")
    say()
    lift = float(dec["actual"].iloc[-1] / dec["actual"].iloc[0])
    mono = int((dec["actual"].diff().dropna() > 0).sum())
    say(f"The top decile clicks **{lift:.1f}x** more often than the bottom one, "
        f"and actual CTR rises with predicted across {mono} of "
        f"{len(dec)-1} decile steps.")
    say()
    say("The predicted column sits slightly below actual in the middle deciles. "
        "That is the rolling recalibration lagging a rising base rate, and it is "
        "discussed in the README - the raw uncalibrated model is closer in "
        "aggregate (ratio 1.005) but worse bin-by-bin.")

    # ==================================================================
    say()
    say("## 2. Ranked candidate lists for two chat contexts")
    say()
    say("Six candidate ads, each with a bid and a brand-safety cap declaring the "
        "spiciest character tier the advertiser will sit next to. Two of them "
        "(`AD_NEW_RPG`, `AD_STREAMING`) are nearly new, with almost no "
        "impressions behind them.")
    say()
    say("Score is `pCTR_with_exploration_bonus x bid x pacing x fatigue x diversity`.")

    cands = build_candidates()
    pacer = BudgetPacer(
        daily_budget={"ADV_GAMES": 8000.0, "ADV_DATE": 8000.0, "ADV_BEVERAGE": 8000.0,
                      "ADV_FINANCE": 1000.0, "ADV_MEDIA": 8000.0},
        spend_today={"ADV_GAMES": 3200.0, "ADV_DATE": 1800.0, "ADV_BEVERAGE": 3900.0,
                     "ADV_FINANCE": 970.0, "ADV_MEDIA": 4100.0},
    )
    ranker = CandidateRanker(
        scorer=scorer, pacer=pacer, fatigue=FatigueTracker(),
        ad_impression_counts={k: float(v) for k, v in AD_IMPRESSIONS.items()},
        explore_z=1.0, prior_ctr=float(test["click"].mean()),
    )

    picks = [
        ("A", test[(test.safety_tier == "sfw") & (test.conversation_turn <= 2)].iloc[0]),
        ("B", test[(test.safety_tier == "mature") & (test.conversation_turn >= 15)].iloc[0]),
    ]

    for tag, row in picks:
        ctx = ctx_from_row(row)
        cid = ctx.character_id
        name = chars.loc[cid, "character_name"] if cid in chars.index else "?"
        desc = chars.loc[cid, "character_description"] if cid in chars.index else "?"

        say()
        say(f"### Context {tag}")
        say()
        say(f"- **character**: `{name}` - {desc}")
        say(f"- **safety tier**: `{ctx.safety_tier}` | **creator**: "
            f"`{ctx.creator_type}` | **lifetime interactions**: {ctx.num_interactions:,}")
        say(f"- **conversation**: message {ctx.conversation_turn} of "
            f"{ctx.session_msg_count}")
        say(f"- **surface**: site `{ctx.site_id}`, app `{ctx.app_id}`, "
            f"hour `{ctx.hour}` (UTC)")
        say()

        ranked = ranker.rank(ctx, cands, fraction_of_day_elapsed=0.6)
        tbl = pd.DataFrame([{
            "rank": r.rank, "ad": r.ad_id, "advertiser": r.advertiser_id,
            "pCTR": round(r.p_ctr, 4), "pCTR+ucb": round(r.p_ctr_ucb, 4),
            "bid": r.bid_cpc, "pace": round(r.pacing_mult, 2),
            "fatigue": round(r.fatigue_mult, 2), "div": round(r.diversity_mult, 2),
            "score": round(r.final_score, 4),
        } for r in ranked])
        say("```")
        say(tbl.to_string(index=False))
        say("```")
        say()
        say("Why each ad landed where it did:")
        say()
        for r in ranked:
            say(f"- **{r.ad_id}** (rank {r.rank}): {r.reason}")

        blocked = getattr(ranker, "_last_blocked", [])
        if blocked:
            say()
            say("Removed **before** scoring - brand safety is a filter, not a "
                "score penalty, so no bid is large enough to buy past it:")
            say()
            for c, why in blocked:
                say(f"- **{c.ad_id}** (bid ${c.bid_cpc:.2f}, cap "
                    f"`{c.max_safety_tier}`): {why}")

    say()
    say("### What changes between the two contexts")
    say()
    say("The ordering is not fixed. Context B is a `mature` character, which "
        "removes every advertiser capped at `sfw` before scoring - including "
        "`AD_BANK_CARD`, the highest bid in the slate at $5.00. The remaining "
        "ads also reorder, because the model's estimate for a given ad moves "
        "with the surface, device and character it is being shown against.")
    say()
    say("The two cold ads carry a visible exploration bonus in both contexts. "
        "That bonus is a function of how many impressions the ad has already "
        "accumulated, so it decays on its own as data arrives - there is no "
        "separate new-ad code path and no graduation threshold to tune.")

    (REPORTS / "sample_output.md").write_text("\n".join(OUT))
    print(f"Wrote {REPORTS/'sample_output.md'}")


if __name__ == "__main__":
    main()
